Unit totCMDS;

Interface

Const

  totGkAltA =   286;    totGkAltB =   304;      totGkAltC =   302;
  totGkAltD =   288;    totGkAltE =   274;      totGkAltF  =  289;
  totGkAltG  =  290;    totGkAltH  =  291;      totGkAltI  =  279;
  totGkAltJ  =  292;    totGkAltK  =  293;      totGkAltL  =  294;
  totGkAltM  =  306;    totGkAltN  =  305;      totGkAltO  =  280;
  totGkAltP  =  281;    totGkAltQ  =  272;      totGkAltR  =  275;
  totGkAltS  =  287;    totGkAltT  =  276;      totGkAltU  =  278;
  totGkAltV  =  303;    totGkAltW  =  273;      totGkAltX  =  301;
  totGkAltY  =  277;    totGkAltZ  =  300;

  totGkF1 =  315; totGkSF1  = 340;  totGkAF1  =   360; totGkCF1  =  350;
  totGkF2 =  316; totGkSF2  = 341;  totGkAF2  =   361; totGkCF2  =  351;
  totGkF3 =  317; totGkSF3  = 342;  totGkAF3  =   362; totGkCF3  =  352;
  totGkF4 =  318; totGkSF4  = 343;  totGkAF4  =   363; totGkCF4  =  353;
  totGkF5 =  319; totGkSF5  = 344;  totGkAF5  =   364; totGkCF5  =  354;
  totGkF6 =  320; totGkSF6  = 345;  totGkAF6  =   365; totGkCF6  =  355;
  totGkF7 =  321; totGkSF7  = 346;  totGkAF7  =   366; totGkCF7  =  356;
  totGkF8 =  322; totGkSF8  = 347;  totGkAF8  =   367; totGkCF8  =  357;
  totGkF9 =  323; totGkSF9  = 348;  totGkAF9  =   368; totGkCF9  =  358;
  totGkF10=  324; totGkSF10 = 349;  totGkAF10 =   369; totGkCF10 =  359;
  totGkF11=  389; totGkSF11 = 391;  totGkAF11 =   395; totGkCF11 =  393;
  totGkF12=  390; totGkSF12 = 392;  totGkAF12 =   396; totGkCF12 =  394;

  totGkBkSp  = 8  ;                     totGkABkSp  = 270; totGkCBkSp  = 127;
  totGkUp    = 328; totGkSUp    =  428; totGkAUp    = 408; totGkCUp    = 397;
  totGkDown  = 336; totGkSDown  =  436; totGkADown  = 416; totGkCDown  = 401;
  totGkLeft  = 331; totGkSLeft  =  431; totGkALeft  = 411; totGkCLeft  = 371;
  totGkRight = 333; totGkSRight =  433; totGkARight = 413; totGkCRight = 372;
  totGkEnd   = 335; totGkSEnd   =  435; totGkAEnd   = 415; totGkCEnd   = 373;
  totGkHome  = 327; totGkSHome  =  427; totGkAHome  = 407; totGkCHome  = 375;
  totGkPgUp  = 329; totGkSPgUp  =  429; totGkAPgUp  = 409; totGkCPgUp  = 388;
  totGkPgDn  = 337; totGkSPdDn  =  437; totGkAPgDn  = 417; totGkCPgDn  = 374;
  totGkIns   = 338; totGkSIns   =  261; totGkAIns   = 418; totGkCIns   = 260;
  totGkDel   = 339; totGkSDel   =  263; totGkADel   = 419; totGkCDel   = 262;
  totGkTab   = 9  ; totGkSTab   =  271; totGkATab   = 421; totGkCTab   = 404;
  totGkEsc   = 27 ;                     totGkAEsc   = 257;



           totWGkLeftC        = 513;      totWGkClose   = 600;
           totWGkRightC       = 514;      totWGkMove    = 601;
           totWGkMiddleC      = 515;      totWGkResize  = 602;
           totWGkLeftRightC   = 516;      totWGkScUp    = 610;
           totWGkLeftMiddleC  = 517;      totWGkScDown  = 611;
           totWGkMiddleRightC = 518;      totWGkScLeft  = 612;
           totWGkAllC         = 519;      totWGkScRight = 613;
           totWGkLeftD        = 523;      totWGkVE      = 614;
           totWGkRightD       = 524;      totWGkHE      = 615;
           totWGkMiddleD      = 525;
           totWGkUp           = 584;
           totWGkDown         = 592;
           totWGkLeft         = 589;
           totWGkRight        = 587;
Implementation


End.

